### PR TITLE
Allow component configs in gulpfile

### PR DESCRIPTION
**Pull request by sttts**
Component configs were refused by gulp-expect.

### CODE REVIEW

**Comment by ohohoreilly** [comment]
@sttts how did you test this change?

**Comment by sttts** [comment]
I did this test, leading to an gulp-expect error before the patch:

``` bash
echo '{ "foo": "bar" }' > components/dashboard/config/production.json
npm run build
cat shared/config/generated-config.js 
```

The last line should include the `{ "foo": "bar" }`.

**Comment by sttts** [comment]
The error message in master:

```
[09:58:52] ✗ FAIL: components/dashboard/config/production.json is unexpected
```

**Comment by ohohoreilly** [comment]
LGTM

**Pull request closed without merging**
