### PR TITLE
acutually rebuild v5

### PR DESCRIPTION
**Pull request by mikedanese**
@jdef take two.

### CODE REVIEW

**Comment by jdef** [comment]
thanks for doing this. i see there's an /app/\* file in there. git warned me about those because they're in `.gitignore`. should we really be committing that file in this PR?

**Comment by mikedanese** [comment]
It's already tracked in the tree... https://github.com/kubernetes/kube-ui/blob/master/app/assets/js/app.js

git add -A . wanted to include it. Maybe clean up seperately if those need not be included?

**Comment by jdef** [comment]
ok sounds good

**Comment by ohohoreilly** [comment]
LGTM

**Comment by mikedanese** [comment]
Okay this is pushed now

**Pull request merged**
