### PR TITLE
chore(jsbuild): use minsafe angular DI syntax

### PR DESCRIPTION
**Pull request by sebholstein**
- enables minification in the build process
- fix all source files that are not using the angular minsafe DI syntax
- activate ng-strict-di mode to prevent future bugs
- some small refactorings
- some small bugfixes 

P.S.: @brendandburns I would like to discuss some topics with you (Kubernetes UI related stuff). Maybe you can send me your contact details via mail? Thank you!

### CODE REVIEW

**Comment by ohohoreilly** [comment]
@SebastianM I'd be happy to discuss Kubernetes UI related stuff with you.

**Comment by sebholstein** [comment]
@preillyme Great. So I had this idea of a Kubernetes UI with a great UX a long time ago (https://twitter.com/Sebamueller/status/501087946314092544) but no one responded to my tweet and I had too less time to start such a project alone. Now, that there is a UI (which is really awesome) and I would like to help out on a regular basis.

It could even be possible to do this part-time with the support of my employer. But that's a topic that I would like to discuss in detail with a team member/manager from Google if this could be interesting for the project. 
/cc @brendandburns 

My other questions are:
- Is there a roadmap or anything similar? (Trying to find topics where I can help out)
- I have improvement suggestions that are related to the project structure (refactorings, build process improvements, etc.). Should I create issues to discuss it?
- Is it planned to align the project with Angular2 (and maybe TypeScript)?

**Comment by ohohoreilly** [comment]
LGTM

**Comment by sebholstein** [comment]
Hey @preillyme,

any opinions on this?:

> - Is there a roadmap or anything similar? (Trying to find topics where I can help out)
> - I have improvement suggestions that are related to the project structure (refactorings, build process improvements, etc.). Should I create issues to discuss it?
> - Is it planned to align the project with Angular2 (and maybe TypeScript)?

Maybe we can chat about this at the end of this week?

**Pull request merged**
