### PR TITLE
Show all namespaces by default

### PR DESCRIPTION
**Pull request by stevesloka**
This fixes issue #5 by showing all namespaces by default. The k8sApi now accepts a namespace as parameter or defaults to "all". I would appreciate if someone could sanity check me, I think we need to update the gitignore to leave out the compiled pieces.

### CODE REVIEW

**Comment by thockin** [comment]
Without commenting on the PR, which I did not review, this user's CLA has been manually verified by our lawyers.  This PR may be merged when reviewd and approved.

**Comment by ohohoreilly** [comment]
LGTM

**Comment by stevesloka** [comment]
Sweet thanks for merging! I could of rebased this as well, you're taking my github cred. =)

**Comment by ohohoreilly** [comment]
I didn't rebase anything @stevesloka I simple merged it. I don't understand your comment that I'm taking your GitHub credit? Do you care to explain?

**Comment by stevesloka** [comment]
It doesn't look right to me and I still don't show up in the contributor
list even through there should be 4 commits from me, but no worries. Like I
said in email, bosses looked at repo and didn't see me, so questioned.
Maybe github is being slow or something, sorry for the confusion.

**Comment by ohohoreilly** [comment]
@stevesloka you can clearly see you did the work and I just merged it. We should add you as a contributor as well once you get a few more commits in the repo. @mikedanese can help with that moving forward. Thanks again for your work.

**Comment by mikedanese** [comment]
@stevesloka make sure the email you signed the commit with is attached to your github account

**Comment by mikedanese** [comment]
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#common-reasons-that-contributions-are-not-counted

**Comment by ohohoreilly** [comment]
Thanks for the link @mikedanese

**Comment by stevesloka** [comment]
Thanks for the info guys, again sorry for the confusion. I'll do some more digging.

**Comment by ohohoreilly** [comment]
Good luck @stevesloka and once again thanks for your contributions.

**Pull request merged**
